### ISSUE TITLE
หน้า candidates ไม่มีลิงค์ให้กดกลับไปหน้าหลักครับ

### ISSUE THREAD

**Issue by ninearif** [codeforthailand/dataset-election-62-candidates#1]
หน้า candidates ไม่มีลิงค์ให้กดกลับไปหน้าหลักครับ

https://github.com/codeforthailand/dataset-election-62-candidates/blob/e4ff79960247d3a0e2983c88cfaecfc1f3ac3833/election62/templates/layout.html#L56

**Comment by heytitle** [comment]
ว่าง สร้าง PR ไหมครับ?

**Comment by heytitle** [comment]
@ninearif the issue was fixed at https://github.com/codeforthailand/dataset-election-62-candidates/commit/b52bc1647452edc3d1d206d884159e65767b29d9.

you can test it here : http://pat.chormai.org/election-62-staging/

We'll deploy the new version soon!
