### ISSUE TITLE
ขอให้การ ค้นประวัติ เป็นการเปิดหน้าใหม่

### ISSUE THREAD

**Issue by aprilboy8434** [codeforthailand/dataset-election-62-candidates#3]
เพื่อไม่ให้เสียเวลากด Back อยากให้การกดค้นประวัติ เป็นการเปิดหน้าใหม่ครับ

**Comment by heytitle** [comment]
Thanks for suggestion. It supposes to be that way. 👍 

fixed in https://github.com/codeforthailand/dataset-election-62-candidates/commit/b7e8c081459916f0fd3183ec8ec20b86c0f28511
