### ISSUE TITLE
Wrong party and logo for the candidate

### ISSUE THREAD

**Issue by bluenex** [codeforthailand/dataset-election-62-candidates#6]
I've seen this from [a Facebook post of a candidate in my zone](https://web.facebook.com/erawanofficial/photos/a.2259590290975517/2291763067758239). I have checked [this page](https://elect.in.th/candidates/z/%E0%B8%81%E0%B8%A3%E0%B8%B8%E0%B8%87%E0%B9%80%E0%B8%97%E0%B8%9E%E0%B8%A1%E0%B8%AB%E0%B8%B2%E0%B8%99%E0%B8%84%E0%B8%A3-12.html) out and it's actually wrong as seen below.

![image](https://user-images.githubusercontent.com/11027706/52913979-bfef0600-32f5-11e9-8d57-83c7c3f49550.png)

Data in the file used to render seems to be correct but I still can't figure it out myself what is going wrong. Could you guys have a look at this? 😄 

https://github.com/codeforthailand/dataset-election-62-candidates/blob/6f48e697dd6cac88e4da81a2f8952630f7b31255/data/election-62-candidates.csv#L221

PS. Do you have any channel to report wrong data? It seems there are more that is not my zone.

**Comment by heytitle** [comment]
@bluenex thanks for reporting! We updated the file hours ago, but we haven't deployed the change yet. 

If you want, you can test the change on our staging server http://pat.chormai.org/election-62-staging. 

We've also created a google form to report missing data, http://bit.ly/election62-missing-data
.

We're more than welcome to receive reports from you! 🍻
