### ISSUE TITLE
Adding "Debate Portal"

### ISSUE THREAD

**Issue by MicroBenz** [codeforthailand/dataset-election-62-candidates#9]
คิดว่าน่าจะดีเรามีหน้าไว้รวม video จากการดีเบตต่างๆ ไว้ในเว็บ เช่น ดีเบตของช่อง 9

**Comment by heytitle** [comment]
Thanks for suggestion. I like the idea. 

How should we list those videos?  by theme or channel? 

any idea @phoneee?

**Comment by phoneee** [comment]
หาเองอาจจะไม่ไหว
คิดว่าน่าจะเปิดช่องให้คนส่งมาเป็น cloud source ดีกว่า
แบบว่าให้เขา submit video link พร้อม tag ผู้ดีเบทมา เดี๋ยวเราหาวิธีแสดงผลกัน

**Comment by heytitle** [comment]
@phoneee @MicroBenz 

I think we can start simple. We create a webpage and use a db file that has the following content:
```
# YAML Format
https://youtu.be/1HR-147FTR0?t=317:
   tags: วิสัยทัศน์, สุขภาพ, แก้จน 
   participating_parties: พลังประชารัฐ, ..., ... 
```
The webpage will have a JS that allow users to filter videos for a particular tag. 

Regarding the data, we can start with a couple of videos and provide a link to suggest new videos.
<img width="500" alt="image" src="https://user-images.githubusercontent.com/1214890/53947017-842aad80-40f7-11e9-8011-4d6c3fff5959.png">

**Comment by heytitle** [comment]
Thanks for the suggestion. Sadly, we didn't have time to implement this. Maybe next time :)?

I"m going to close this issue for now.
